before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: C7r9F11X+ZVB5j0sBz5nZpM5/CULc9sU0hdD+UM8EY5MAhwYosEmG9QLe1HSf2t5KP86gYMCMLSnAgmr9te52SfHbHaxS08BLrze/+OOEJYItPBjTu/BS6Wip+aspOGx3XS/7JBaHL4O8me+2rtcE4/lOA/9Z7lwp/PntNkl5iEPOodK18/DmEoDIBVOKGuFb0/x3IiaY+nnDgjrZtCDdS7HRcJwfM1Q+/FVN5oQWk1i0795er+57/S4YmqywwGnzLaxwThFJ8ehPIobDj5WhbWGcHP4/PCYrwH9EqGRWUwaCU6wIBwkL4dADjALJZH2PMWsKvVFGmR4SQSLx8bC19l5bYF4SAJQEIo041x4meGyffq8Fx2JUbPOZaOpqsjn0uWuqm+4YR7He9MQojsl+mbKFnoUnE8FLf35VAEZdMDeBKw7Wj+0RhWwhqknGKGoyCr82WvNd52p6trWOYvtWVLPV4KBaJlAoo5TkZwCyLRQjap5oRe93oQ9i21yPvD4aZ93EJl6sY5WVlUlFws8PV62NlwW1k2KJNUIXJfNnEfe5528MUK/9YWYjAdBVTo6DRNS14tOUI22FOuabhntrPRh+6IQsQRJsSLuTD7Patr81SkA+UQEr+zQCaz7R0XB5UltINWM5hj7pQqUGTlI/l5mtXljBoKRUYnJyIZhReQ= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
